# -*- coding: utf-8 -*-
"""AI Homework 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11D1obEGokNETthnTICZUm8aKslg6vIh_
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import datasets
from sklearn.linear_model import Perceptron

iris = datasets.load_iris();

print(iris.feature_names)
print(iris.target_names)

versicolor_pl = iris.data[50:56]
virginica_pl = iris.data[100:106]
tl = np.arange(10) + 1
r = (0,0,0,0,0,1,1,1,1,1,0,1)
pl = np.concatenate((versicolor_pl[0:5,2],virginica_pl[0:5,2]))
print(versicolor_pl[5])
print(virginica_pl[5])
print(r)

table1 = pd.DataFrame({"t":tl,"x":pl[:10],"r":r[:10]})
print(table1)

model = Perceptron()
model.fit(np.concatenate((versicolor_pl[0:5],virginica_pl[0:5])),table1["r"][:10])



plt.scatter(table1["x"],table1["r"])
w=97
w0=-5*w
a = np.arange(4,6,0.1)
y = a*w+w0    #actual output
plt.plot(a,1/(1+np.exp(-y)),'r')
plt.xlabel('Petal length')
plt.ylabel('p (probability of virginica)');

print(versicolor_pl[5,2] , "---" ,virginica_pl[5,2])
y = versicolor_pl[5,2]*w+w0
print(1/(1+np.exp(-y)),"Should be 0")
y = virginica_pl[5,2]*w+w0
print((1/(1+np.exp(-y)),"Should be 1"))

y = (versicolor_pl[5,2]+1)*w+w0
print(1/(1+np.exp(-y)),"Should be 0")
y = (virginica_pl[5,2]+1)*w+w0
print((1/(1+np.exp(-y)),"Should be 1"))

print(w0)
w = w + -0.1375
w0 = w0 + -0.025
print(w)
print(w0)

y = (5.008)*w+w0
print(1/(1+np.exp(-y)))

y = (versicolor_pl[5,2]+1)*w+w0
print(1/(1+np.exp(-y)),"Should be 0")
y = (virginica_pl[5,2]+1)*w+w0
print((1/(1+np.exp(-y)),"Should be 1"))



versicolor_leftovers = iris.data[56:100][:,2]
for x in range(44):
  y = (versicolor_leftovers[x])*w+w0
  print(1/(1+np.exp(-y)))

virginica_leftovers = iris.data[106:150][:,2]
for x in range(44):
  y = (virginica_leftovers[x])*w+w0
  print(1/(1+np.exp(-y)))









